[metadata]
  name = "Treinamento Go"
  version = "0.0.1"
  author = "Vagner Praia"
  email = "vagnerpraia@gmail.com"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/globalsign/mgo"
  version = "r2018.06.15"